//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USportsNews.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Yazar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Yazar()
        {
            this.Tbl_Haber = new HashSet<Tbl_Haber>();
        }
    
        public int YazarID { get; set; }
        public string YazarAdi { get; set; }
        public string YazarSoyadi { get; set; }
        public string YazarEposta { get; set; }
        public string YazarTel { get; set; }
        public string YazarParola { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Haber> Tbl_Haber { get; set; }
    }
}
