//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USportsNews.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Admin
    {
        public int AdminID { get; set; }
        public string AdminAdi { get; set; }
        public string AdminSoyadi { get; set; }
        public string AdminEposta { get; set; }
        public string AdminParola { get; set; }
        public string AdminTelNo { get; set; }
        public Nullable<int> HaberID { get; set; }
    
        public virtual Tbl_Haber Tbl_Haber { get; set; }
    }
}
